### ISSUE TITLE
Check that new database revisions don't trip up functions

### ISSUE THREAD

**Issue by Dave-Keith** [Mar-scal/Assessment_fns#40]
A couple of new columns were added to the database, just need to check and make sure they don't trip up any of our calcs.  99% sure we're fine or the error would result in obvious issues so not a high priority .

**Comment by freyakeyser** [comment]
I checked on this, and presently the new column is only added to the sampling **table**, but not the **views** that are actually called into survey summary. Eventually if they are added to the views (i.e. for use in the survey summary analysis), this may be a small problem, but it looks like get_offshore_survey functions does select by column names, so I don't think we'd get unexpected results accidentally.

**Comment by Dave-Keith** [comment]
I just took a peek and agree, I'm going to close this issue as I can see no way this would impact anything given how get_offshore_survey is coded.
